"""Markdown Support

Revision ID: 94d1b89800bc
Revises: 2249b6f75238
Create Date: 2016-08-18 16:31:09.183000

"""

# revision identifiers, used by Alembic.
revision = '94d1b89800bc'
down_revision = '2249b6f75238'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
