"""Avatar

Revision ID: aab200d787d8
Revises: 5281b49757e8
Create Date: 2016-08-17 10:58:37.119000

"""

# revision identifiers, used by Alembic.
revision = 'aab200d787d8'
down_revision = '5281b49757e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
